# Generated by Django 5.0.6 on 2024-06-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_taom_buyurtma'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='manzil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='tolov_usuli',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
