# Generated by Django 5.0.6 on 2024-06-28 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_buyurtma_manzil_buyurtma_tolov_usuli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savatcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('manzil', models.CharField(blank=True, max_length=255, null=True)),
                ('tolov_usuli', models.CharField(blank=True, max_length=50, null=True)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.buyurtma')),
                ('taom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.taom')),
            ],
        ),
    ]
