# Generated by Django 5.0.6 on 2024-06-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_savatcha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Savatcha',
        ),
    ]
