# Generated by Django 5.0.6 on 2024-07-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_delete_savatcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
