# Generated by Django 5.0.6 on 2024-07-02 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_buyurtma_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyurtma',
            name='likes',
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_quality', models.IntegerField()),
                ('service_quality', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.buyurtma')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='custom_auth_id_050deb_idx')],
            },
        ),
    ]
